version: '3'

tasks:
  # Update this repo with the copier-template
  # `--vcs-ref HEAD` to avoid `You are downgrading from 0.1.0.post2.dev0+0a9a33e to 0.1.0. Downgrades are not supported.`
  update:
    cmds:
      - |
        copier update --vcs-ref HEAD .
